# Generated by Django 2.2.1 on 2019-05-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_book_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_pic', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
